#!/usr/bin/env python

import sys
import os
import os.path

this_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.append( os.path.dirname(this_dir) )

from kamino.mind import roles
from kamino.mind import definition
from kamino.mind import udev_to_json




#print 'JSON: ', definition.load( '/home/thomas.cocagne/devel/ktest/d.json' )
def load_ktest():
    try:
        rm = roles.RoleManager( '/home/thomas.cocagne/devel/ktest' )
        
        rlst = rm._roles.values()
        rlst.sort( key = lambda r: len(r.parents) )
        
        for r in rlst:
            print '{0:*^80}'.format( '{0} [{1}]'.format(r.role_name, ', '.join(x.role_name for x in r.parents ) ) )
            for k,v in r.globals_ident.iteritems():
                print '{0:15} = {1:40} {2}'.format( k, r.globals[k], v )
        
    except roles.RoleDefinitionError, e:
        print str(e)



#udev_to_json.print_devs( udev_to_json.get_subsys('sound') )
#udev_to_json.printem( 'block' )
jd = udev_to_json.get_jdisks()

import json

print json.dumps( jd, sort_keys=True, indent=4 )
